export const initialState = {
  commentsTotal: 0,
  repliesTotal: 0,
  appVersion: '',
  phpVersion: '',
  gd_loaded: false,
  gdVersion: '',
  registerGlobals: '',
  magicQuotesGPC: '',
  zipSupport: '',
  themes: {},
  timezones: {},
  languages: {},
  dateFormates: {},
};
